root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - '@react-native-community'
  - plugin:jsdoc/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
plugins:
  - '@typescript-eslint'
  - jsdoc
  - jest
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _
      caughtErrorsIgnorePattern: _
  no-shadow: warn
  no-shadow-restricted-names: error
  prettier/prettier: off
  react-native/sort-styles: off
  react/react-in-jsx-scope: warn
  no-trailing-spaces:
    - error
    - ignoreComments: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
  jsdoc/check-access: warn
  jsdoc/check-alignment: warn
  jsdoc/check-examples: off
  jsdoc/check-indentation: off
  jsdoc/check-line-alignment: off
  jsdoc/check-param-names: warn
  jsdoc/check-property-names: warn
  jsdoc/check-syntax: off
  jsdoc/check-tag-names: warn
  jsdoc/check-types: warn
  jsdoc/check-values: warn
  jsdoc/empty-tags: warn
  jsdoc/implements-on-classes: warn
  jsdoc/multiline-blocks: warn
  jsdoc/no-bad-blocks: off
  jsdoc/no-defaults: off
  jsdoc/no-missing-syntax: off
  jsdoc/no-multi-asterisks: warn
  jsdoc/no-restricted-syntax: off
  jsdoc/no-types: off
  jsdoc/no-undefined-types: warn
  jsdoc/require-asterisk-prefix: warn
  jsdoc/require-description: warn
  jsdoc/require-description-complete-sentence: off
  jsdoc/require-example: off
  jsdoc/require-file-overview: off
  jsdoc/require-hyphen-before-param-description: warn
  jsdoc/require-jsdoc: off
  jsdoc/require-param: warn
  jsdoc/require-param-description: warn
  jsdoc/require-param-name: warn
  jsdoc/require-param-type: warn
  jsdoc/require-property: warn
  jsdoc/require-property-description: warn
  jsdoc/require-property-name: warn
  jsdoc/require-property-type: warn
  jsdoc/require-returns: warn
  jsdoc/require-returns-check: warn
  jsdoc/require-returns-description: warn
  jsdoc/require-returns-type: warn
  jsdoc/require-throws: off
  jsdoc/require-yields: warn
  jsdoc/require-yields-check: warn
  jsdoc/sort-tags: off
  jsdoc/tag-lines: warn
  jsdoc/valid-types: warn
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
ignorePatterns:
  - '**/node_modules/'
  - '**/lib/'
  - '**/scripts/'
env:
  jest/globals: true
  jest: true
  commonjs: true
  node: true
